package fakelpm

import (
	"encoding/base64"
	"encoding/hex"
)

var (
	SampleMeasurements = []string{
		"RDQ4N0U4MTExODI1MDYwNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODlGMjAwMTQwMDk0NkU2MTZENjEwMUZFRkZGRkZGMTgwMzAxMDA4N0U4MTExODI2MDYwNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODlGMzAwMTUwMDI3NDYyNzQ2NTkwMUZFRkZGRkZGMTgwMzAxMDA=",
		"RDQ4N0U4MTExODI3MDYwNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODlGMjAwMTQwMEJBNkU2NTZFNTkwMUZFRkZGRkZGMTkwMzAxMDA4N0U4MTExODMzMDYwNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODlGMDAwMTQwMEU1NkQ5QjZENUUwMUZFRkZGRkZGMTkwMzAxMDA=",
		"RDQ4N0U4MTExODQwMDYwNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODlGMTAwMTkwMDM2NkYwNTZGNEMwMUZFRkZGRkZGMTkwMzAxMDA4N0U4MTExODQyMDYwNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODlGMjAwMTUwMDEzNkQ4OTZDNEYwMUZFRkZGRkZGMTkwMzAxMDA=",
		"RDQ4N0U4MTExODQzMDYwNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODlGMTAwMTIwMEQ0NkM2OTZCNjIwMUZFRkZGRkZGMTkwMzAxMDA4N0U4MTExODQ1MDYwNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODlGMjAwMTQwMDlDNkY4RjZGNEQwMUZFRkZGRkZGMTkwMzAxMDA=",
		"RDQ4N0U4MTExODQ2MDYwNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODlGMzAwMTIwMDM3NkUyOTZFNTcwMUZFRkZGRkZGMTkwMzAxMDA4N0U4MTExODQ5MDYwNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODlGMzAwMTQwMDExNkVERjZENEYwMUZFRkZGRkZGMTkwMzAxMDA=",
		"RDQ4N0U4MTExODUxMDYwNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODlGMTAwMTIwMEYzNDVGMjQ1NUMwMUZFRkZGRkZGMTkwMzAxMDA4N0U4MTExODUyMDYwNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODlGMDAwMTQwMDBGNkQwMTZENTAwMUZFRkZGRkZGMTkwMzAxMDA=",
	}
	currentSampleIndex = 0
)

func GetNextMeasurement() ([]byte, error) {
	if len(SampleMeasurements) == 0 {
		return nil, nil
	}

	sample := SampleMeasurements[currentSampleIndex]
	currentSampleIndex = (currentSampleIndex + 1) % len(SampleMeasurements)
	return base64.StdEncoding.DecodeString(sample)
}

func BuildACKResponse() []byte {
	return []byte{STX, 'P', 'C', 'R', '0', 'A', 'C', 'K', '1', 'A', ETX}
}

func BuildNAKResponse() []byte {
	return []byte{STX, 'P', 'C', 'R', '0', 'N', 'A', 'K', '0', 'F', ETX}
}

func BuildACKMeasureResponse() []byte {
	return []byte{STX, 'P', 'C', 'R', '0', 'M', 'S', 'R', '0', 'F', ETX}
}

func BuildEndFrameResponse() []byte {
	// Example end frame from documentation
	endFrame := "02 50 43 52 31 45 33 38 37 31 30 30 37 32 33 33 31 37 31 03"
	data, _ := hex.DecodeString(endFrame)
	return data
}
